import React, { useState, useRef } from 'react';
import axios from 'axios';
import { Upload, File as FileIcon, CheckCircle, AlertCircle, Loader2 } from 'lucide-react';

const FileUploadSample = () => {
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [uploadStatus, setUploadStatus] = useState<'idle' | 'uploading' | 'success' | 'error'>('idle');
    const [uploadedUrl, setUploadedUrl] = useState<string>('');
    const fileInputRef = useRef<HTMLInputElement>(null);

    const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        if (event.target.files && event.target.files[0]) {
            setSelectedFile(event.target.files[0]);
            setUploadStatus('idle');
        }
    };

    const handleUpload = async () => {
        if (!selectedFile) return;

        const formData = new FormData();
        // CRITICAL FIX: Match the backend 'file' field name exactly!
        formData.append('file', selectedFile); 

        try {
            setUploadStatus('uploading');
            
            const response = await axios.post('http://localhost:5000/api/upload', formData, {
                headers: { 'Content-Type': 'multipart/form-data' }
            });

            // Read the dynamic url generated by your controller
            setUploadedUrl(response.data.url);
            setUploadStatus('success');
        } catch (error) {
            console.error("Upload Error Encountered:", error);
            setUploadStatus('error');
        }
    };

    const handleClearFile = (e: React.MouseEvent) => {
        e.preventDefault();
        e.stopPropagation();
        setSelectedFile(null);
        setUploadStatus('idle');
        if (fileInputRef.current) fileInputRef.current.value = '';
    };

    return (
        <div className="max-w-xl mx-auto p-8 bg-white rounded-[2rem] shadow-sm border border-slate-100 animate-in fade-in slide-in-from-bottom-4 duration-500">
            <h2 className="text-xl font-black text-slate-800 mb-6 flex items-center gap-2">
                <Upload className="text-[#003d3d]" size={22} /> Admin Media Upload
            </h2>

            <div className="space-y-6">
                <label className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed border-slate-200 hover:border-[#003d3d] rounded-[1.5rem] cursor-pointer hover:bg-slate-50/50 transition-all group relative overflow-hidden">
                    <div className="flex flex-col items-center justify-center px-4 pt-5 pb-6 text-center">
                        <FileIcon className={`w-10 h-10 mb-3 transition-colors ${selectedFile ? 'text-[#003d3d]' : 'text-slate-400 group-hover:text-slate-600'}`} />
                        
                        {selectedFile ? (
                            <div className="space-y-1 max-w-sm">
                                <p className="text-sm font-bold text-slate-800 truncate px-2">
                                    {selectedFile.name}
                                </p>
                                <p className="text-[11px] text-slate-400 font-medium">
                                    {(selectedFile.size / (1024 * 1024)).toFixed(2)} MB
                                </p>
                            </div>
                        ) : (
                            <div>
                                <p className="text-sm font-bold text-slate-700 mb-0.5">Click to browse media files</p>
                                <p className="text-xs text-slate-400 font-medium">Supports images up to 5MB</p>
                            </div>
                        )}
                    </div>
                    
                    <input 
                        type="file" 
                        ref={fileInputRef}
                        className="hidden" 
                        onChange={handleFileChange} 
                    />

                    {selectedFile && uploadStatus !== 'uploading' && (
                        <button
                            onClick={handleClearFile}
                            className="absolute top-3 right-3 w-7 h-7 rounded-full bg-slate-100 hover:bg-rose-50 text-slate-400 hover:text-rose-500 font-bold text-sm flex items-center justify-center transition-all shadow-sm"
                        >
                            ×
                        </button>
                    )}
                </label>

                <button
                    onClick={handleUpload}
                    disabled={!selectedFile || uploadStatus === 'uploading'}
                    className={`w-full py-3.5 rounded-2xl font-black text-sm tracking-wide shadow-sm transition-all flex items-center justify-center gap-2 active:scale-[0.99] ${
                        !selectedFile 
                            ? 'bg-slate-100 text-slate-400 cursor-not-allowed' 
                            : 'bg-[#003d3d] text-white hover:bg-[#002828] shadow-md shadow-teal-900/10'
                    }`}
                >
                    {uploadStatus === 'uploading' ? (
                        <>
                            <Loader2 className="animate-spin" size={18} />
                            <span>Uploading File Asset...</span>
                        </>
                    ) : (
                        <span>Start Upload</span>
                    )}
                </button>

                {uploadStatus === 'success' && (
                    <div className="p-4 bg-teal-50/50 rounded-2xl border border-teal-100/60 flex flex-col gap-2.5 animate-in fade-in zoom-in-95 duration-200">
                        <div className="flex items-center gap-2 text-teal-800 font-bold text-xs uppercase tracking-wider">
                            <CheckCircle size={16} className="text-teal-600" /> Upload Complete!
                        </div>
                        <div className="flex gap-2 items-center">
                            <input 
                                readOnly 
                                onClick={(e) => (e.target as HTMLInputElement).select()}
                                value={uploadedUrl} 
                                className="w-full text-[11px] font-mono bg-white border border-slate-200/60 p-2.5 rounded-xl text-slate-600 cursor-pointer shadow-sm focus:outline-none"
                            />
                        </div>
                    </div>
                )}

                {uploadStatus === 'error' && (
                    <div className="p-4 bg-rose-50/60 rounded-2xl border border-rose-100/80 flex items-center gap-2.5 text-rose-800 font-bold text-xs uppercase tracking-wider animate-in shake duration-200">
                        <AlertCircle size={16} className="text-rose-500" /> Upload failed. Try again.
                    </div>
                )}
            </div>
        </div>
    );
};

export default FileUploadSample;